apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: twoplusone
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
    - port: 80        # Ingress가 붙는 포트
      targetPort: 8080
